name: 1.1.1.$(rev:rrr)

trigger:
  branches:
    include:
    - master

schedules:
- cron: 0 5 * * 6
  branches:
    include:
    - master
  always: true

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Bujild.SourcesDirectory)\PELoaderLib.sln'
    arguments: '--configuration $(buildConfiguration)'
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)\PELoaderLib\PELoaderLib\bin\$(buildConfiguration)\**\*
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
